"""add_school_status

Revision ID: 69a764dd1636
Revises: c01f9c61743e
Create Date: 2026-09-08 21:37:39.072171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a764dd1636'
down_revision: Union[str, None] = 'c01f9c61743e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('status', sa.String(length=50), server_default='PENDING', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'status')
    # ### end Alembic commands ###
